import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class", '[data-theme="dark"]'],
  content: ["./src/**/*.{ts,tsx}", "./apps/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: {
          base: "var(--surface-base)",
          raised: "var(--surface-raised)",
          sunken: "var(--surface-sunken)",
        },
        content: {
          primary: "var(--content-primary)",
          secondary: "var(--content-secondary)",
          placeholder: "var(--content-placeholder)",
          muted: "var(--content-muted)",
          inverse: "var(--content-inverse)",
        },
        // Direct semantic shorthands
        primary: "var(--content-primary)",
        secondary: "var(--content-secondary)",
        placeholder: "var(--content-placeholder)",
        error: "var(--feedback-danger)",
        action: {
          primary: "var(--action-primary)",
          "primary-hover": "var(--action-primary-hover)",
          destructive: "var(--action-destructive)",
        },
        border: {
          primary: "var(--border-primary)",
          subtle: "var(--border-subtle)",
          strong: "var(--border-strong)",
        },
        status: {
          error: "var(--feedback-danger)",
          success: "var(--feedback-success)",
          warning: "var(--feedback-warning)",
        },
      },
      spacing: {
        // Figma primitive scale (space.* & spacing.*)
        0: "var(--ds-space-0, var(--ds-spacing-0))",
        2: "var(--ds-space-2, var(--ds-spacing-2))",
        4: "var(--ds-space-4, var(--ds-spacing-4))",
        8: "var(--ds-space-8, var(--ds-spacing-8))",
        10: "var(--ds-space-10, var(--ds-spacing-10))",
        12: "var(--ds-space-12, var(--ds-spacing-12))",
        14: "var(--ds-space-14, var(--ds-spacing-14))",
        16: "var(--ds-space-16, var(--ds-spacing-16))",
        20: "var(--ds-space-20, var(--ds-spacing-20))",
        24: "var(--ds-space-24, var(--ds-spacing-24))",
        32: "var(--ds-space-32, var(--ds-spacing-32))",
        40: "var(--ds-spacing-40)",
        48: "var(--ds-space-48, var(--ds-spacing-48))",
        64: "var(--ds-space-64, var(--ds-spacing-64))",
        80: "var(--ds-spacing-80)",
        96: "var(--ds-spacing-96)",
        // Semantic size scale (T-shirt)
        none: "var(--ds-space-none)",
        "3xs": "var(--ds-space-3xs)",
        "2xs": "var(--ds-space-2xs)",
        xs: "var(--ds-space-xs)",
        "sm-compact": "var(--ds-space-sm-compact)",
        sm: "var(--ds-space-sm)",
        "md-compact": "var(--ds-space-md-compact)",
        md: "var(--ds-space-md)",
        lg: "var(--ds-space-lg)",
        xl: "var(--ds-space-xl)",
        "2xl": "var(--ds-space-2xl)",
        "3xl": "var(--ds-space-3xl)",
        "4xl": "var(--ds-space-4xl)",
        // Semantic intent - Gap
        "gap-none": "var(--ds-space-gap-none)",
        "gap-3xs": "var(--ds-space-gap-3xs)",
        "gap-2xs": "var(--ds-space-gap-2xs)",
        "gap-xs": "var(--ds-space-gap-xs)",
        "gap-sm": "var(--ds-space-gap-sm)",
        "gap-md": "var(--ds-space-gap-md)",
        "gap-lg": "var(--ds-space-gap-lg)",
        "gap-xl": "var(--ds-space-gap-xl)",
        "gap-2xl": "var(--ds-space-gap-2xl)",
        // Semantic intent - Inset
        "inset-none": "var(--ds-space-inset-none)",
        "inset-3xs": "var(--ds-space-inset-3xs)",
        "inset-2xs": "var(--ds-space-inset-2xs)",
        "inset-xs": "var(--ds-space-inset-xs)",
        "inset-sm": "var(--ds-space-inset-sm)",
        "inset-md": "var(--ds-space-inset-md)",
        "inset-lg": "var(--ds-space-inset-lg)",
        "inset-xl": "var(--ds-space-inset-xl)",
        "inset-2xl": "var(--ds-space-inset-2xl)",
        // Semantic intent - Layout
        "layout-gutter": "var(--ds-space-layout-gutter)",
        "layout-gutter-desktop": "var(--ds-space-layout-gutter-desktop)",
        "layout-card": "var(--ds-space-layout-card)",
        "layout-section": "var(--ds-space-layout-section)",
        "layout-container": "var(--ds-space-layout-container)",
        "layout-page": "var(--ds-space-layout-page)",
      },
      borderRadius: {
        // Figma primitive scale
        0: "var(--ds-radius-0)",
        2: "var(--ds-radius-2)",
        4: "var(--ds-radius-4)",
        5: "var(--ds-radius-5)",
        6: "var(--ds-radius-6)",
        8: "var(--ds-radius-8)",
        12: "var(--ds-radius-12)",
        16: "var(--ds-radius-16)",
        999: "var(--ds-radius-999)",
        Full: "var(--ds-radius-full)",
        // Semantic scale
        none: "var(--ds-radius-none)",
        "3xs": "var(--ds-radius-3xs)",
        "2xs": "var(--ds-radius-2xs)",
        xs: "var(--ds-radius-xs)",
        sm: "var(--ds-radius-sm)",
        md: "var(--ds-radius-md)",
        lg: "var(--ds-radius-lg)",
        xl: "var(--ds-radius-xl)",
        full: "var(--ds-radius-full)",
        // Semantic intent
        control: "var(--ds-radius-control)",
        button: "var(--ds-radius-button)",
        input: "var(--ds-radius-input)",
        field: "var(--ds-radius-field)",
        select: "var(--ds-radius-select)",
        container: "var(--ds-radius-container)",
        modal: "var(--ds-radius-modal)",
        dialog: "var(--ds-radius-dialog)",
        drawer: "var(--ds-radius-drawer)",
        "sub-container": "var(--ds-radius-sub-container)",
        card: "var(--ds-radius-card)",
        dropdown: "var(--ds-radius-dropdown)",
        menu: "var(--ds-radius-menu)",
        popover: "var(--ds-radius-popover)",
        toast: "var(--ds-radius-toast)",
        image: "var(--ds-radius-image)",
        media: "var(--ds-radius-media)",
        thumbnail: "var(--ds-radius-thumbnail)",
        uploader: "var(--ds-radius-uploader)",
        badge: "var(--ds-radius-badge)",
        tag: "var(--ds-radius-tag)",
        chip: "var(--ds-radius-chip)",
        checkbox: "var(--ds-radius-checkbox)",
        tooltip: "var(--ds-radius-tooltip)",
        indicator: "var(--ds-radius-indicator)",
        pill: "var(--ds-radius-pill)",
        circle: "var(--ds-radius-circle)",
        avatar: "var(--ds-radius-avatar)",
        switch: "var(--ds-radius-switch)",
        radio: "var(--ds-radius-radio)",
      },
      opacity: {
        // Figma primitive scale
        0: "var(--ds-opacity-0)",
        25: "var(--ds-opacity-25)",
        50: "var(--ds-opacity-50)",
        75: "var(--ds-opacity-75)",
        100: "var(--ds-opacity-100)",
        // Semantic scale & intent
        transparent: "var(--ds-opacity-transparent)",
        subtle: "var(--ds-opacity-subtle)",
        semi: "var(--ds-opacity-semi)",
        dim: "var(--ds-opacity-dim)",
        solid: "var(--ds-opacity-solid)",
        disabled: "var(--ds-opacity-disabled)",
        hover: "var(--ds-opacity-hover)",
        "hover-subtle": "var(--ds-opacity-hover-subtle)",
        overlay: "var(--ds-opacity-overlay)",
        divider: "var(--ds-opacity-divider)",
        active: "var(--ds-opacity-active)",
        invisible: "var(--ds-opacity-invisible)",
      },
    },
  },
  plugins: [],
};

export default config;
