#!/usr/bin/env node
/**
 * SisapDS token build.
 *
 * Reads W3C DTCG token files from tokens/base and tokens/semantic, resolves
 * `{alias}` references, and emits:
 *
 *   tokens/build/tokens.css          — CSS custom properties (:root + [data-theme="dark"])
 *   tokens/build/tailwind-theme.css  — Tailwind v4 `@theme inline` mapping
 *
 * Source of truth is tokens/*.json — never edit anything in tokens/build.
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const readJson = (path) => JSON.parse(readFileSync(path, "utf8"));

const readDirJson = (dir) =>
  readdirSync(dir)
    .filter((f) => f.endsWith(".json"))
    .sort()
    .map((f) => readJson(join(dir, f)));

/** Flatten a DTCG object into { "path.to.token": node } where node carries $value. */
function flatten(obj, prefix = "", out = {}) {
  for (const [key, value] of Object.entries(obj)) {
    const path = prefix ? `${prefix}.${key}` : key;
    if (value && typeof value === "object" && !Array.isArray(value)) {
      if ("$value" in value) out[path] = value;
      else flatten(value, path, out);
    }
  }
  return out;
}

const mergeFlattened = (...sets) => Object.assign({}, ...sets);

/** Resolve one (possibly aliased) token value; detects circular references. */
function resolveValue(path, tokens, stack) {
  if (stack.has(path)) {
    throw new Error(`Circular token reference involving "${path}"`);
  }
  stack.add(path);
  const node = tokens[path];
  if (!node) throw new Error(`Unknown token reference "{${path}}"`);
  return substitute(String(node.$value), tokens, stack);
}

function substitute(value, tokens, stack) {
  return value.replace(/\{([^{}]+)\}/g, (_, ref) => resolveValue(ref.trim(), tokens, stack));
}

const kebab = (s) =>
  s
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[\s_]+/g, "-")
    .replace(/\./g, "-")
    .toLowerCase();

const base = mergeFlattened(
  ...readDirJson(join(repoRoot, "tokens/base")).map((json) => flatten(json)),
);
const light = flatten(readJson(join(repoRoot, "tokens/semantic/light.json")));
const dark = flatten(readJson(join(repoRoot, "tokens/semantic/dark.json")));

// Dark inherits everything from base + light, then overrides what it redefines.
const themes = {
  light: mergeFlattened(base, light),
  dark: mergeFlattened(base, light, dark),
};

function renderVars(tokens) {
  const sorted = Object.keys(tokens).sort();
  return sorted
    .map((path) => {
      const value = substitute(String(tokens[path].$value), tokens, new Set([path]));
      return `  --ds-${kebab(path)}: ${value};`;
    })
    .join("\n");
}

function renderTailwindTheme(tokens) {
  const lines = Object.keys(tokens)
    .sort()
    .flatMap((path) => {
      const varName = `--ds-${kebab(path)}`;
      if (path.startsWith("color.")) {
        return [`  --color-${kebab(path.slice("color.".length))}: var(${varName});`];
      }
      if (path.startsWith("radii.")) {
        return [`  --radius-${kebab(path.slice("radii.".length))}: var(${varName});`];
      }
      if (path.startsWith("typography.font.family.")) {
        return [`  --font-${kebab(path.slice("typography.font.family.".length))}: var(${varName});`];
      }
      if (path.startsWith("typography.font.size.")) {
        return [`  --text-${kebab(path.slice("typography.font.size.".length))}: var(${varName});`];
      }
      return [];
    });
  return lines.join("\n");
}

const generatedBanner =
  "/* GENERATED by scripts/build-tokens.mjs — do not edit.\n   Source of truth: tokens/base + tokens/semantic (W3C DTCG). */\n\n";

const tokensCss =
  generatedBanner +
  `:root {\n  color-scheme: light;\n\n${renderVars(themes.light)}\n}\n\n[data-theme="dark"] {\n  color-scheme: dark;\n\n${renderVars(themes.dark)}\n}\n`;

const tailwindThemeCss =
  generatedBanner + `@theme inline {\n${renderTailwindTheme(themes.light)}\n}\n`;

const buildDir = join(repoRoot, "tokens/build");
mkdirSync(buildDir, { recursive: true });
writeFileSync(join(buildDir, "tokens.css"), tokensCss);
writeFileSync(join(buildDir, "tailwind-theme.css"), tailwindThemeCss);

console.log(
  `[tokens] ${Object.keys(themes.light).length} tokens (light) / ${Object.keys(themes.dark).length} (dark) → tokens/build/tokens.css + tailwind-theme.css`,
);
